/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as ProximosPasosRouteImport } from './routes/proximos-pasos'
import { Route as MiembrosRouteImport } from './routes/miembros'
import { Route as InvitacionesRouteImport } from './routes/invitaciones'
import { Route as EntregablesRouteImport } from './routes/entregables'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as ComunicacionRouteImport } from './routes/comunicacion'
import { Route as ActualizacionesRouteImport } from './routes/actualizaciones'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiciosSeoRouteImport } from './routes/servicios.seo'
import { Route as ServiciosGoHighLevelRouteImport } from './routes/servicios.go-high-level'
import { Route as ServiciosDisenoWebRouteImport } from './routes/servicios.diseno-web'
import { Route as ServiciosAgentesIaRouteImport } from './routes/servicios.agentes-ia'

const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProximosPasosRoute = ProximosPasosRouteImport.update({
  id: '/proximos-pasos',
  path: '/proximos-pasos',
  getParentRoute: () => rootRouteImport,
} as any)
const MiembrosRoute = MiembrosRouteImport.update({
  id: '/miembros',
  path: '/miembros',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitacionesRoute = InvitacionesRouteImport.update({
  id: '/invitaciones',
  path: '/invitaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregablesRoute = EntregablesRouteImport.update({
  id: '/entregables',
  path: '/entregables',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicacionRoute = ComunicacionRouteImport.update({
  id: '/comunicacion',
  path: '/comunicacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualizacionesRoute = ActualizacionesRouteImport.update({
  id: '/actualizaciones',
  path: '/actualizaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosSeoRoute = ServiciosSeoRouteImport.update({
  id: '/servicios/seo',
  path: '/servicios/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosGoHighLevelRoute = ServiciosGoHighLevelRouteImport.update({
  id: '/servicios/go-high-level',
  path: '/servicios/go-high-level',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosDisenoWebRoute = ServiciosDisenoWebRouteImport.update({
  id: '/servicios/diseno-web',
  path: '/servicios/diseno-web',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosAgentesIaRoute = ServiciosAgentesIaRouteImport.update({
  id: '/servicios/agentes-ia',
  path: '/servicios/agentes-ia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actualizaciones': typeof ActualizacionesRoute
  '/comunicacion': typeof ComunicacionRoute
  '/configuracion': typeof ConfiguracionRoute
  '/entregables': typeof EntregablesRoute
  '/invitaciones': typeof InvitacionesRoute
  '/miembros': typeof MiembrosRoute
  '/proximos-pasos': typeof ProximosPasosRoute
  '/recursos': typeof RecursosRoute
  '/resultados': typeof ResultadosRoute
  '/servicios/agentes-ia': typeof ServiciosAgentesIaRoute
  '/servicios/diseno-web': typeof ServiciosDisenoWebRoute
  '/servicios/go-high-level': typeof ServiciosGoHighLevelRoute
  '/servicios/seo': typeof ServiciosSeoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actualizaciones': typeof ActualizacionesRoute
  '/comunicacion': typeof ComunicacionRoute
  '/configuracion': typeof ConfiguracionRoute
  '/entregables': typeof EntregablesRoute
  '/invitaciones': typeof InvitacionesRoute
  '/miembros': typeof MiembrosRoute
  '/proximos-pasos': typeof ProximosPasosRoute
  '/recursos': typeof RecursosRoute
  '/resultados': typeof ResultadosRoute
  '/servicios/agentes-ia': typeof ServiciosAgentesIaRoute
  '/servicios/diseno-web': typeof ServiciosDisenoWebRoute
  '/servicios/go-high-level': typeof ServiciosGoHighLevelRoute
  '/servicios/seo': typeof ServiciosSeoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actualizaciones': typeof ActualizacionesRoute
  '/comunicacion': typeof ComunicacionRoute
  '/configuracion': typeof ConfiguracionRoute
  '/entregables': typeof EntregablesRoute
  '/invitaciones': typeof InvitacionesRoute
  '/miembros': typeof MiembrosRoute
  '/proximos-pasos': typeof ProximosPasosRoute
  '/recursos': typeof RecursosRoute
  '/resultados': typeof ResultadosRoute
  '/servicios/agentes-ia': typeof ServiciosAgentesIaRoute
  '/servicios/diseno-web': typeof ServiciosDisenoWebRoute
  '/servicios/go-high-level': typeof ServiciosGoHighLevelRoute
  '/servicios/seo': typeof ServiciosSeoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actualizaciones'
    | '/comunicacion'
    | '/configuracion'
    | '/entregables'
    | '/invitaciones'
    | '/miembros'
    | '/proximos-pasos'
    | '/recursos'
    | '/resultados'
    | '/servicios/agentes-ia'
    | '/servicios/diseno-web'
    | '/servicios/go-high-level'
    | '/servicios/seo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actualizaciones'
    | '/comunicacion'
    | '/configuracion'
    | '/entregables'
    | '/invitaciones'
    | '/miembros'
    | '/proximos-pasos'
    | '/recursos'
    | '/resultados'
    | '/servicios/agentes-ia'
    | '/servicios/diseno-web'
    | '/servicios/go-high-level'
    | '/servicios/seo'
  id:
    | '__root__'
    | '/'
    | '/actualizaciones'
    | '/comunicacion'
    | '/configuracion'
    | '/entregables'
    | '/invitaciones'
    | '/miembros'
    | '/proximos-pasos'
    | '/recursos'
    | '/resultados'
    | '/servicios/agentes-ia'
    | '/servicios/diseno-web'
    | '/servicios/go-high-level'
    | '/servicios/seo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActualizacionesRoute: typeof ActualizacionesRoute
  ComunicacionRoute: typeof ComunicacionRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  EntregablesRoute: typeof EntregablesRoute
  InvitacionesRoute: typeof InvitacionesRoute
  MiembrosRoute: typeof MiembrosRoute
  ProximosPasosRoute: typeof ProximosPasosRoute
  RecursosRoute: typeof RecursosRoute
  ResultadosRoute: typeof ResultadosRoute
  ServiciosAgentesIaRoute: typeof ServiciosAgentesIaRoute
  ServiciosDisenoWebRoute: typeof ServiciosDisenoWebRoute
  ServiciosGoHighLevelRoute: typeof ServiciosGoHighLevelRoute
  ServiciosSeoRoute: typeof ServiciosSeoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proximos-pasos': {
      id: '/proximos-pasos'
      path: '/proximos-pasos'
      fullPath: '/proximos-pasos'
      preLoaderRoute: typeof ProximosPasosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miembros': {
      id: '/miembros'
      path: '/miembros'
      fullPath: '/miembros'
      preLoaderRoute: typeof MiembrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitaciones': {
      id: '/invitaciones'
      path: '/invitaciones'
      fullPath: '/invitaciones'
      preLoaderRoute: typeof InvitacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregables': {
      id: '/entregables'
      path: '/entregables'
      fullPath: '/entregables'
      preLoaderRoute: typeof EntregablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicacion': {
      id: '/comunicacion'
      path: '/comunicacion'
      fullPath: '/comunicacion'
      preLoaderRoute: typeof ComunicacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualizaciones': {
      id: '/actualizaciones'
      path: '/actualizaciones'
      fullPath: '/actualizaciones'
      preLoaderRoute: typeof ActualizacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/seo': {
      id: '/servicios/seo'
      path: '/servicios/seo'
      fullPath: '/servicios/seo'
      preLoaderRoute: typeof ServiciosSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/go-high-level': {
      id: '/servicios/go-high-level'
      path: '/servicios/go-high-level'
      fullPath: '/servicios/go-high-level'
      preLoaderRoute: typeof ServiciosGoHighLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/diseno-web': {
      id: '/servicios/diseno-web'
      path: '/servicios/diseno-web'
      fullPath: '/servicios/diseno-web'
      preLoaderRoute: typeof ServiciosDisenoWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/agentes-ia': {
      id: '/servicios/agentes-ia'
      path: '/servicios/agentes-ia'
      fullPath: '/servicios/agentes-ia'
      preLoaderRoute: typeof ServiciosAgentesIaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActualizacionesRoute: ActualizacionesRoute,
  ComunicacionRoute: ComunicacionRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  EntregablesRoute: EntregablesRoute,
  InvitacionesRoute: InvitacionesRoute,
  MiembrosRoute: MiembrosRoute,
  ProximosPasosRoute: ProximosPasosRoute,
  RecursosRoute: RecursosRoute,
  ResultadosRoute: ResultadosRoute,
  ServiciosAgentesIaRoute: ServiciosAgentesIaRoute,
  ServiciosDisenoWebRoute: ServiciosDisenoWebRoute,
  ServiciosGoHighLevelRoute: ServiciosGoHighLevelRoute,
  ServiciosSeoRoute: ServiciosSeoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
