/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as ProximosPasosRouteImport } from './routes/proximos-pasos'
import { Route as MiembrosRouteImport } from './routes/miembros'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvitacionesRouteImport } from './routes/invitaciones'
import { Route as EntregablesRouteImport } from './routes/entregables'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as ComunicacionRouteImport } from './routes/comunicacion'
import { Route as ActualizacionesRouteImport } from './routes/actualizaciones'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResultadosIndexRouteImport } from './routes/resultados.index'
import { Route as ComunicacionIndexRouteImport } from './routes/comunicacion.index'
import { Route as ServiciosSeoRouteImport } from './routes/servicios.seo'
import { Route as ServiciosGoHighLevelRouteImport } from './routes/servicios.go-high-level'
import { Route as ServiciosDisenoWebRouteImport } from './routes/servicios.diseno-web'
import { Route as ServiciosAgentesIaRouteImport } from './routes/servicios.agentes-ia'
import { Route as ResultadosSitioWebRouteImport } from './routes/resultados.sitio-web'
import { Route as ResultadosSeoGmbRouteImport } from './routes/resultados.seo-gmb'
import { Route as ResultadosGoHighLevelRouteImport } from './routes/resultados.go-high-level'
import { Route as ResultadosAgentesIaRouteImport } from './routes/resultados.agentes-ia'
import { Route as ComunicacionWhatsappRouteImport } from './routes/comunicacion.whatsapp'
import { Route as ComunicacionEmailRouteImport } from './routes/comunicacion.email'
import { Route as ComunicacionAgendarRouteImport } from './routes/comunicacion.agendar'

const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProximosPasosRoute = ProximosPasosRouteImport.update({
  id: '/proximos-pasos',
  path: '/proximos-pasos',
  getParentRoute: () => rootRouteImport,
} as any)
const MiembrosRoute = MiembrosRouteImport.update({
  id: '/miembros',
  path: '/miembros',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitacionesRoute = InvitacionesRouteImport.update({
  id: '/invitaciones',
  path: '/invitaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregablesRoute = EntregablesRouteImport.update({
  id: '/entregables',
  path: '/entregables',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicacionRoute = ComunicacionRouteImport.update({
  id: '/comunicacion',
  path: '/comunicacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualizacionesRoute = ActualizacionesRouteImport.update({
  id: '/actualizaciones',
  path: '/actualizaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosIndexRoute = ResultadosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResultadosRoute,
} as any)
const ComunicacionIndexRoute = ComunicacionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComunicacionRoute,
} as any)
const ServiciosSeoRoute = ServiciosSeoRouteImport.update({
  id: '/servicios/seo',
  path: '/servicios/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosGoHighLevelRoute = ServiciosGoHighLevelRouteImport.update({
  id: '/servicios/go-high-level',
  path: '/servicios/go-high-level',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosDisenoWebRoute = ServiciosDisenoWebRouteImport.update({
  id: '/servicios/diseno-web',
  path: '/servicios/diseno-web',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosAgentesIaRoute = ServiciosAgentesIaRouteImport.update({
  id: '/servicios/agentes-ia',
  path: '/servicios/agentes-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosSitioWebRoute = ResultadosSitioWebRouteImport.update({
  id: '/sitio-web',
  path: '/sitio-web',
  getParentRoute: () => ResultadosRoute,
} as any)
const ResultadosSeoGmbRoute = ResultadosSeoGmbRouteImport.update({
  id: '/seo-gmb',
  path: '/seo-gmb',
  getParentRoute: () => ResultadosRoute,
} as any)
const ResultadosGoHighLevelRoute = ResultadosGoHighLevelRouteImport.update({
  id: '/go-high-level',
  path: '/go-high-level',
  getParentRoute: () => ResultadosRoute,
} as any)
const ResultadosAgentesIaRoute = ResultadosAgentesIaRouteImport.update({
  id: '/agentes-ia',
  path: '/agentes-ia',
  getParentRoute: () => ResultadosRoute,
} as any)
const ComunicacionWhatsappRoute = ComunicacionWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => ComunicacionRoute,
} as any)
const ComunicacionEmailRoute = ComunicacionEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => ComunicacionRoute,
} as any)
const ComunicacionAgendarRoute = ComunicacionAgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => ComunicacionRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actualizaciones': typeof ActualizacionesRoute
  '/comunicacion': typeof ComunicacionRouteWithChildren
  '/configuracion': typeof ConfiguracionRoute
  '/entregables': typeof EntregablesRoute
  '/invitaciones': typeof InvitacionesRoute
  '/login': typeof LoginRoute
  '/miembros': typeof MiembrosRoute
  '/proximos-pasos': typeof ProximosPasosRoute
  '/recursos': typeof RecursosRoute
  '/resultados': typeof ResultadosRouteWithChildren
  '/comunicacion/agendar': typeof ComunicacionAgendarRoute
  '/comunicacion/email': typeof ComunicacionEmailRoute
  '/comunicacion/whatsapp': typeof ComunicacionWhatsappRoute
  '/resultados/agentes-ia': typeof ResultadosAgentesIaRoute
  '/resultados/go-high-level': typeof ResultadosGoHighLevelRoute
  '/resultados/seo-gmb': typeof ResultadosSeoGmbRoute
  '/resultados/sitio-web': typeof ResultadosSitioWebRoute
  '/servicios/agentes-ia': typeof ServiciosAgentesIaRoute
  '/servicios/diseno-web': typeof ServiciosDisenoWebRoute
  '/servicios/go-high-level': typeof ServiciosGoHighLevelRoute
  '/servicios/seo': typeof ServiciosSeoRoute
  '/comunicacion/': typeof ComunicacionIndexRoute
  '/resultados/': typeof ResultadosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actualizaciones': typeof ActualizacionesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/entregables': typeof EntregablesRoute
  '/invitaciones': typeof InvitacionesRoute
  '/login': typeof LoginRoute
  '/miembros': typeof MiembrosRoute
  '/proximos-pasos': typeof ProximosPasosRoute
  '/recursos': typeof RecursosRoute
  '/comunicacion/agendar': typeof ComunicacionAgendarRoute
  '/comunicacion/email': typeof ComunicacionEmailRoute
  '/comunicacion/whatsapp': typeof ComunicacionWhatsappRoute
  '/resultados/agentes-ia': typeof ResultadosAgentesIaRoute
  '/resultados/go-high-level': typeof ResultadosGoHighLevelRoute
  '/resultados/seo-gmb': typeof ResultadosSeoGmbRoute
  '/resultados/sitio-web': typeof ResultadosSitioWebRoute
  '/servicios/agentes-ia': typeof ServiciosAgentesIaRoute
  '/servicios/diseno-web': typeof ServiciosDisenoWebRoute
  '/servicios/go-high-level': typeof ServiciosGoHighLevelRoute
  '/servicios/seo': typeof ServiciosSeoRoute
  '/comunicacion': typeof ComunicacionIndexRoute
  '/resultados': typeof ResultadosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actualizaciones': typeof ActualizacionesRoute
  '/comunicacion': typeof ComunicacionRouteWithChildren
  '/configuracion': typeof ConfiguracionRoute
  '/entregables': typeof EntregablesRoute
  '/invitaciones': typeof InvitacionesRoute
  '/login': typeof LoginRoute
  '/miembros': typeof MiembrosRoute
  '/proximos-pasos': typeof ProximosPasosRoute
  '/recursos': typeof RecursosRoute
  '/resultados': typeof ResultadosRouteWithChildren
  '/comunicacion/agendar': typeof ComunicacionAgendarRoute
  '/comunicacion/email': typeof ComunicacionEmailRoute
  '/comunicacion/whatsapp': typeof ComunicacionWhatsappRoute
  '/resultados/agentes-ia': typeof ResultadosAgentesIaRoute
  '/resultados/go-high-level': typeof ResultadosGoHighLevelRoute
  '/resultados/seo-gmb': typeof ResultadosSeoGmbRoute
  '/resultados/sitio-web': typeof ResultadosSitioWebRoute
  '/servicios/agentes-ia': typeof ServiciosAgentesIaRoute
  '/servicios/diseno-web': typeof ServiciosDisenoWebRoute
  '/servicios/go-high-level': typeof ServiciosGoHighLevelRoute
  '/servicios/seo': typeof ServiciosSeoRoute
  '/comunicacion/': typeof ComunicacionIndexRoute
  '/resultados/': typeof ResultadosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actualizaciones'
    | '/comunicacion'
    | '/configuracion'
    | '/entregables'
    | '/invitaciones'
    | '/login'
    | '/miembros'
    | '/proximos-pasos'
    | '/recursos'
    | '/resultados'
    | '/comunicacion/agendar'
    | '/comunicacion/email'
    | '/comunicacion/whatsapp'
    | '/resultados/agentes-ia'
    | '/resultados/go-high-level'
    | '/resultados/seo-gmb'
    | '/resultados/sitio-web'
    | '/servicios/agentes-ia'
    | '/servicios/diseno-web'
    | '/servicios/go-high-level'
    | '/servicios/seo'
    | '/comunicacion/'
    | '/resultados/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actualizaciones'
    | '/configuracion'
    | '/entregables'
    | '/invitaciones'
    | '/login'
    | '/miembros'
    | '/proximos-pasos'
    | '/recursos'
    | '/comunicacion/agendar'
    | '/comunicacion/email'
    | '/comunicacion/whatsapp'
    | '/resultados/agentes-ia'
    | '/resultados/go-high-level'
    | '/resultados/seo-gmb'
    | '/resultados/sitio-web'
    | '/servicios/agentes-ia'
    | '/servicios/diseno-web'
    | '/servicios/go-high-level'
    | '/servicios/seo'
    | '/comunicacion'
    | '/resultados'
  id:
    | '__root__'
    | '/'
    | '/actualizaciones'
    | '/comunicacion'
    | '/configuracion'
    | '/entregables'
    | '/invitaciones'
    | '/login'
    | '/miembros'
    | '/proximos-pasos'
    | '/recursos'
    | '/resultados'
    | '/comunicacion/agendar'
    | '/comunicacion/email'
    | '/comunicacion/whatsapp'
    | '/resultados/agentes-ia'
    | '/resultados/go-high-level'
    | '/resultados/seo-gmb'
    | '/resultados/sitio-web'
    | '/servicios/agentes-ia'
    | '/servicios/diseno-web'
    | '/servicios/go-high-level'
    | '/servicios/seo'
    | '/comunicacion/'
    | '/resultados/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActualizacionesRoute: typeof ActualizacionesRoute
  ComunicacionRoute: typeof ComunicacionRouteWithChildren
  ConfiguracionRoute: typeof ConfiguracionRoute
  EntregablesRoute: typeof EntregablesRoute
  InvitacionesRoute: typeof InvitacionesRoute
  LoginRoute: typeof LoginRoute
  MiembrosRoute: typeof MiembrosRoute
  ProximosPasosRoute: typeof ProximosPasosRoute
  RecursosRoute: typeof RecursosRoute
  ResultadosRoute: typeof ResultadosRouteWithChildren
  ServiciosAgentesIaRoute: typeof ServiciosAgentesIaRoute
  ServiciosDisenoWebRoute: typeof ServiciosDisenoWebRoute
  ServiciosGoHighLevelRoute: typeof ServiciosGoHighLevelRoute
  ServiciosSeoRoute: typeof ServiciosSeoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proximos-pasos': {
      id: '/proximos-pasos'
      path: '/proximos-pasos'
      fullPath: '/proximos-pasos'
      preLoaderRoute: typeof ProximosPasosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miembros': {
      id: '/miembros'
      path: '/miembros'
      fullPath: '/miembros'
      preLoaderRoute: typeof MiembrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitaciones': {
      id: '/invitaciones'
      path: '/invitaciones'
      fullPath: '/invitaciones'
      preLoaderRoute: typeof InvitacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregables': {
      id: '/entregables'
      path: '/entregables'
      fullPath: '/entregables'
      preLoaderRoute: typeof EntregablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicacion': {
      id: '/comunicacion'
      path: '/comunicacion'
      fullPath: '/comunicacion'
      preLoaderRoute: typeof ComunicacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualizaciones': {
      id: '/actualizaciones'
      path: '/actualizaciones'
      fullPath: '/actualizaciones'
      preLoaderRoute: typeof ActualizacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados/': {
      id: '/resultados/'
      path: '/'
      fullPath: '/resultados/'
      preLoaderRoute: typeof ResultadosIndexRouteImport
      parentRoute: typeof ResultadosRoute
    }
    '/comunicacion/': {
      id: '/comunicacion/'
      path: '/'
      fullPath: '/comunicacion/'
      preLoaderRoute: typeof ComunicacionIndexRouteImport
      parentRoute: typeof ComunicacionRoute
    }
    '/servicios/seo': {
      id: '/servicios/seo'
      path: '/servicios/seo'
      fullPath: '/servicios/seo'
      preLoaderRoute: typeof ServiciosSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/go-high-level': {
      id: '/servicios/go-high-level'
      path: '/servicios/go-high-level'
      fullPath: '/servicios/go-high-level'
      preLoaderRoute: typeof ServiciosGoHighLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/diseno-web': {
      id: '/servicios/diseno-web'
      path: '/servicios/diseno-web'
      fullPath: '/servicios/diseno-web'
      preLoaderRoute: typeof ServiciosDisenoWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/agentes-ia': {
      id: '/servicios/agentes-ia'
      path: '/servicios/agentes-ia'
      fullPath: '/servicios/agentes-ia'
      preLoaderRoute: typeof ServiciosAgentesIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados/sitio-web': {
      id: '/resultados/sitio-web'
      path: '/sitio-web'
      fullPath: '/resultados/sitio-web'
      preLoaderRoute: typeof ResultadosSitioWebRouteImport
      parentRoute: typeof ResultadosRoute
    }
    '/resultados/seo-gmb': {
      id: '/resultados/seo-gmb'
      path: '/seo-gmb'
      fullPath: '/resultados/seo-gmb'
      preLoaderRoute: typeof ResultadosSeoGmbRouteImport
      parentRoute: typeof ResultadosRoute
    }
    '/resultados/go-high-level': {
      id: '/resultados/go-high-level'
      path: '/go-high-level'
      fullPath: '/resultados/go-high-level'
      preLoaderRoute: typeof ResultadosGoHighLevelRouteImport
      parentRoute: typeof ResultadosRoute
    }
    '/resultados/agentes-ia': {
      id: '/resultados/agentes-ia'
      path: '/agentes-ia'
      fullPath: '/resultados/agentes-ia'
      preLoaderRoute: typeof ResultadosAgentesIaRouteImport
      parentRoute: typeof ResultadosRoute
    }
    '/comunicacion/whatsapp': {
      id: '/comunicacion/whatsapp'
      path: '/whatsapp'
      fullPath: '/comunicacion/whatsapp'
      preLoaderRoute: typeof ComunicacionWhatsappRouteImport
      parentRoute: typeof ComunicacionRoute
    }
    '/comunicacion/email': {
      id: '/comunicacion/email'
      path: '/email'
      fullPath: '/comunicacion/email'
      preLoaderRoute: typeof ComunicacionEmailRouteImport
      parentRoute: typeof ComunicacionRoute
    }
    '/comunicacion/agendar': {
      id: '/comunicacion/agendar'
      path: '/agendar'
      fullPath: '/comunicacion/agendar'
      preLoaderRoute: typeof ComunicacionAgendarRouteImport
      parentRoute: typeof ComunicacionRoute
    }
  }
}

interface ComunicacionRouteChildren {
  ComunicacionAgendarRoute: typeof ComunicacionAgendarRoute
  ComunicacionEmailRoute: typeof ComunicacionEmailRoute
  ComunicacionWhatsappRoute: typeof ComunicacionWhatsappRoute
  ComunicacionIndexRoute: typeof ComunicacionIndexRoute
}

const ComunicacionRouteChildren: ComunicacionRouteChildren = {
  ComunicacionAgendarRoute: ComunicacionAgendarRoute,
  ComunicacionEmailRoute: ComunicacionEmailRoute,
  ComunicacionWhatsappRoute: ComunicacionWhatsappRoute,
  ComunicacionIndexRoute: ComunicacionIndexRoute,
}

const ComunicacionRouteWithChildren = ComunicacionRoute._addFileChildren(
  ComunicacionRouteChildren,
)

interface ResultadosRouteChildren {
  ResultadosAgentesIaRoute: typeof ResultadosAgentesIaRoute
  ResultadosGoHighLevelRoute: typeof ResultadosGoHighLevelRoute
  ResultadosSeoGmbRoute: typeof ResultadosSeoGmbRoute
  ResultadosSitioWebRoute: typeof ResultadosSitioWebRoute
  ResultadosIndexRoute: typeof ResultadosIndexRoute
}

const ResultadosRouteChildren: ResultadosRouteChildren = {
  ResultadosAgentesIaRoute: ResultadosAgentesIaRoute,
  ResultadosGoHighLevelRoute: ResultadosGoHighLevelRoute,
  ResultadosSeoGmbRoute: ResultadosSeoGmbRoute,
  ResultadosSitioWebRoute: ResultadosSitioWebRoute,
  ResultadosIndexRoute: ResultadosIndexRoute,
}

const ResultadosRouteWithChildren = ResultadosRoute._addFileChildren(
  ResultadosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActualizacionesRoute: ActualizacionesRoute,
  ComunicacionRoute: ComunicacionRouteWithChildren,
  ConfiguracionRoute: ConfiguracionRoute,
  EntregablesRoute: EntregablesRoute,
  InvitacionesRoute: InvitacionesRoute,
  LoginRoute: LoginRoute,
  MiembrosRoute: MiembrosRoute,
  ProximosPasosRoute: ProximosPasosRoute,
  RecursosRoute: RecursosRoute,
  ResultadosRoute: ResultadosRouteWithChildren,
  ServiciosAgentesIaRoute: ServiciosAgentesIaRoute,
  ServiciosDisenoWebRoute: ServiciosDisenoWebRoute,
  ServiciosGoHighLevelRoute: ServiciosGoHighLevelRoute,
  ServiciosSeoRoute: ServiciosSeoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
