/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as SitioWebRouteImport } from './routes/sitio-web'
import { Route as SeoGmbRouteImport } from './routes/seo-gmb'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as ProximosPasosRouteImport } from './routes/proximos-pasos'
import { Route as MiembrosRouteImport } from './routes/miembros'
import { Route as InvitacionesRouteImport } from './routes/invitaciones'
import { Route as GhlRouteImport } from './routes/ghl'
import { Route as EquipoRouteImport } from './routes/equipo'
import { Route as EntregablesRouteImport } from './routes/entregables'
import { Route as EmailRouteImport } from './routes/email'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as ComunicacionRouteImport } from './routes/comunicacion'
import { Route as AgentesIaRouteImport } from './routes/agentes-ia'
import { Route as AgendarRouteImport } from './routes/agendar'
import { Route as ActualizacionesRouteImport } from './routes/actualizaciones'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiciosSeoRouteImport } from './routes/servicios.seo'
import { Route as ServiciosGoHighLevelRouteImport } from './routes/servicios.go-high-level'
import { Route as ServiciosDisenoWebRouteImport } from './routes/servicios.diseno-web'
import { Route as ServiciosAgentesIaRouteImport } from './routes/servicios.agentes-ia'

const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const SitioWebRoute = SitioWebRouteImport.update({
  id: '/sitio-web',
  path: '/sitio-web',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoGmbRoute = SeoGmbRouteImport.update({
  id: '/seo-gmb',
  path: '/seo-gmb',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProximosPasosRoute = ProximosPasosRouteImport.update({
  id: '/proximos-pasos',
  path: '/proximos-pasos',
  getParentRoute: () => rootRouteImport,
} as any)
const MiembrosRoute = MiembrosRouteImport.update({
  id: '/miembros',
  path: '/miembros',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitacionesRoute = InvitacionesRouteImport.update({
  id: '/invitaciones',
  path: '/invitaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const GhlRoute = GhlRouteImport.update({
  id: '/ghl',
  path: '/ghl',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoRoute = EquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregablesRoute = EntregablesRouteImport.update({
  id: '/entregables',
  path: '/entregables',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicacionRoute = ComunicacionRouteImport.update({
  id: '/comunicacion',
  path: '/comunicacion',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentesIaRoute = AgentesIaRouteImport.update({
  id: '/agentes-ia',
  path: '/agentes-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendarRoute = AgendarRouteImport.update({
  id: '/agendar',
  path: '/agendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualizacionesRoute = ActualizacionesRouteImport.update({
  id: '/actualizaciones',
  path: '/actualizaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosSeoRoute = ServiciosSeoRouteImport.update({
  id: '/servicios/seo',
  path: '/servicios/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosGoHighLevelRoute = ServiciosGoHighLevelRouteImport.update({
  id: '/servicios/go-high-level',
  path: '/servicios/go-high-level',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosDisenoWebRoute = ServiciosDisenoWebRouteImport.update({
  id: '/servicios/diseno-web',
  path: '/servicios/diseno-web',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosAgentesIaRoute = ServiciosAgentesIaRouteImport.update({
  id: '/servicios/agentes-ia',
  path: '/servicios/agentes-ia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actualizaciones': typeof ActualizacionesRoute
  '/agendar': typeof AgendarRoute
  '/agentes-ia': typeof AgentesIaRoute
  '/comunicacion': typeof ComunicacionRoute
  '/configuracion': typeof ConfiguracionRoute
  '/documentos': typeof DocumentosRoute
  '/email': typeof EmailRoute
  '/entregables': typeof EntregablesRoute
  '/equipo': typeof EquipoRoute
  '/ghl': typeof GhlRoute
  '/invitaciones': typeof InvitacionesRoute
  '/miembros': typeof MiembrosRoute
  '/proximos-pasos': typeof ProximosPasosRoute
  '/recursos': typeof RecursosRoute
  '/resultados': typeof ResultadosRoute
  '/seo-gmb': typeof SeoGmbRoute
  '/sitio-web': typeof SitioWebRoute
  '/whatsapp': typeof WhatsappRoute
  '/servicios/agentes-ia': typeof ServiciosAgentesIaRoute
  '/servicios/diseno-web': typeof ServiciosDisenoWebRoute
  '/servicios/go-high-level': typeof ServiciosGoHighLevelRoute
  '/servicios/seo': typeof ServiciosSeoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actualizaciones': typeof ActualizacionesRoute
  '/agendar': typeof AgendarRoute
  '/agentes-ia': typeof AgentesIaRoute
  '/comunicacion': typeof ComunicacionRoute
  '/configuracion': typeof ConfiguracionRoute
  '/documentos': typeof DocumentosRoute
  '/email': typeof EmailRoute
  '/entregables': typeof EntregablesRoute
  '/equipo': typeof EquipoRoute
  '/ghl': typeof GhlRoute
  '/invitaciones': typeof InvitacionesRoute
  '/miembros': typeof MiembrosRoute
  '/proximos-pasos': typeof ProximosPasosRoute
  '/recursos': typeof RecursosRoute
  '/resultados': typeof ResultadosRoute
  '/seo-gmb': typeof SeoGmbRoute
  '/sitio-web': typeof SitioWebRoute
  '/whatsapp': typeof WhatsappRoute
  '/servicios/agentes-ia': typeof ServiciosAgentesIaRoute
  '/servicios/diseno-web': typeof ServiciosDisenoWebRoute
  '/servicios/go-high-level': typeof ServiciosGoHighLevelRoute
  '/servicios/seo': typeof ServiciosSeoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actualizaciones': typeof ActualizacionesRoute
  '/agendar': typeof AgendarRoute
  '/agentes-ia': typeof AgentesIaRoute
  '/comunicacion': typeof ComunicacionRoute
  '/configuracion': typeof ConfiguracionRoute
  '/documentos': typeof DocumentosRoute
  '/email': typeof EmailRoute
  '/entregables': typeof EntregablesRoute
  '/equipo': typeof EquipoRoute
  '/ghl': typeof GhlRoute
  '/invitaciones': typeof InvitacionesRoute
  '/miembros': typeof MiembrosRoute
  '/proximos-pasos': typeof ProximosPasosRoute
  '/recursos': typeof RecursosRoute
  '/resultados': typeof ResultadosRoute
  '/seo-gmb': typeof SeoGmbRoute
  '/sitio-web': typeof SitioWebRoute
  '/whatsapp': typeof WhatsappRoute
  '/servicios/agentes-ia': typeof ServiciosAgentesIaRoute
  '/servicios/diseno-web': typeof ServiciosDisenoWebRoute
  '/servicios/go-high-level': typeof ServiciosGoHighLevelRoute
  '/servicios/seo': typeof ServiciosSeoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actualizaciones'
    | '/agendar'
    | '/agentes-ia'
    | '/comunicacion'
    | '/configuracion'
    | '/documentos'
    | '/email'
    | '/entregables'
    | '/equipo'
    | '/ghl'
    | '/invitaciones'
    | '/miembros'
    | '/proximos-pasos'
    | '/recursos'
    | '/resultados'
    | '/seo-gmb'
    | '/sitio-web'
    | '/whatsapp'
    | '/servicios/agentes-ia'
    | '/servicios/diseno-web'
    | '/servicios/go-high-level'
    | '/servicios/seo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actualizaciones'
    | '/agendar'
    | '/agentes-ia'
    | '/comunicacion'
    | '/configuracion'
    | '/documentos'
    | '/email'
    | '/entregables'
    | '/equipo'
    | '/ghl'
    | '/invitaciones'
    | '/miembros'
    | '/proximos-pasos'
    | '/recursos'
    | '/resultados'
    | '/seo-gmb'
    | '/sitio-web'
    | '/whatsapp'
    | '/servicios/agentes-ia'
    | '/servicios/diseno-web'
    | '/servicios/go-high-level'
    | '/servicios/seo'
  id:
    | '__root__'
    | '/'
    | '/actualizaciones'
    | '/agendar'
    | '/agentes-ia'
    | '/comunicacion'
    | '/configuracion'
    | '/documentos'
    | '/email'
    | '/entregables'
    | '/equipo'
    | '/ghl'
    | '/invitaciones'
    | '/miembros'
    | '/proximos-pasos'
    | '/recursos'
    | '/resultados'
    | '/seo-gmb'
    | '/sitio-web'
    | '/whatsapp'
    | '/servicios/agentes-ia'
    | '/servicios/diseno-web'
    | '/servicios/go-high-level'
    | '/servicios/seo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActualizacionesRoute: typeof ActualizacionesRoute
  AgendarRoute: typeof AgendarRoute
  AgentesIaRoute: typeof AgentesIaRoute
  ComunicacionRoute: typeof ComunicacionRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  DocumentosRoute: typeof DocumentosRoute
  EmailRoute: typeof EmailRoute
  EntregablesRoute: typeof EntregablesRoute
  EquipoRoute: typeof EquipoRoute
  GhlRoute: typeof GhlRoute
  InvitacionesRoute: typeof InvitacionesRoute
  MiembrosRoute: typeof MiembrosRoute
  ProximosPasosRoute: typeof ProximosPasosRoute
  RecursosRoute: typeof RecursosRoute
  ResultadosRoute: typeof ResultadosRoute
  SeoGmbRoute: typeof SeoGmbRoute
  SitioWebRoute: typeof SitioWebRoute
  WhatsappRoute: typeof WhatsappRoute
  ServiciosAgentesIaRoute: typeof ServiciosAgentesIaRoute
  ServiciosDisenoWebRoute: typeof ServiciosDisenoWebRoute
  ServiciosGoHighLevelRoute: typeof ServiciosGoHighLevelRoute
  ServiciosSeoRoute: typeof ServiciosSeoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitio-web': {
      id: '/sitio-web'
      path: '/sitio-web'
      fullPath: '/sitio-web'
      preLoaderRoute: typeof SitioWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-gmb': {
      id: '/seo-gmb'
      path: '/seo-gmb'
      fullPath: '/seo-gmb'
      preLoaderRoute: typeof SeoGmbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proximos-pasos': {
      id: '/proximos-pasos'
      path: '/proximos-pasos'
      fullPath: '/proximos-pasos'
      preLoaderRoute: typeof ProximosPasosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miembros': {
      id: '/miembros'
      path: '/miembros'
      fullPath: '/miembros'
      preLoaderRoute: typeof MiembrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitaciones': {
      id: '/invitaciones'
      path: '/invitaciones'
      fullPath: '/invitaciones'
      preLoaderRoute: typeof InvitacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ghl': {
      id: '/ghl'
      path: '/ghl'
      fullPath: '/ghl'
      preLoaderRoute: typeof GhlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo': {
      id: '/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof EquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregables': {
      id: '/entregables'
      path: '/entregables'
      fullPath: '/entregables'
      preLoaderRoute: typeof EntregablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicacion': {
      id: '/comunicacion'
      path: '/comunicacion'
      fullPath: '/comunicacion'
      preLoaderRoute: typeof ComunicacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentes-ia': {
      id: '/agentes-ia'
      path: '/agentes-ia'
      fullPath: '/agentes-ia'
      preLoaderRoute: typeof AgentesIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agendar': {
      id: '/agendar'
      path: '/agendar'
      fullPath: '/agendar'
      preLoaderRoute: typeof AgendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualizaciones': {
      id: '/actualizaciones'
      path: '/actualizaciones'
      fullPath: '/actualizaciones'
      preLoaderRoute: typeof ActualizacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/seo': {
      id: '/servicios/seo'
      path: '/servicios/seo'
      fullPath: '/servicios/seo'
      preLoaderRoute: typeof ServiciosSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/go-high-level': {
      id: '/servicios/go-high-level'
      path: '/servicios/go-high-level'
      fullPath: '/servicios/go-high-level'
      preLoaderRoute: typeof ServiciosGoHighLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/diseno-web': {
      id: '/servicios/diseno-web'
      path: '/servicios/diseno-web'
      fullPath: '/servicios/diseno-web'
      preLoaderRoute: typeof ServiciosDisenoWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/agentes-ia': {
      id: '/servicios/agentes-ia'
      path: '/servicios/agentes-ia'
      fullPath: '/servicios/agentes-ia'
      preLoaderRoute: typeof ServiciosAgentesIaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActualizacionesRoute: ActualizacionesRoute,
  AgendarRoute: AgendarRoute,
  AgentesIaRoute: AgentesIaRoute,
  ComunicacionRoute: ComunicacionRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  DocumentosRoute: DocumentosRoute,
  EmailRoute: EmailRoute,
  EntregablesRoute: EntregablesRoute,
  EquipoRoute: EquipoRoute,
  GhlRoute: GhlRoute,
  InvitacionesRoute: InvitacionesRoute,
  MiembrosRoute: MiembrosRoute,
  ProximosPasosRoute: ProximosPasosRoute,
  RecursosRoute: RecursosRoute,
  ResultadosRoute: ResultadosRoute,
  SeoGmbRoute: SeoGmbRoute,
  SitioWebRoute: SitioWebRoute,
  WhatsappRoute: WhatsappRoute,
  ServiciosAgentesIaRoute: ServiciosAgentesIaRoute,
  ServiciosDisenoWebRoute: ServiciosDisenoWebRoute,
  ServiciosGoHighLevelRoute: ServiciosGoHighLevelRoute,
  ServiciosSeoRoute: ServiciosSeoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
